# Dockerfile for the api using micromamba as environement manager 
# Reduces image size and speeds up builds as opposed to using conda

# Base micromamba
FROM mambaorg/micromamba:1.4.3

WORKDIR /app

COPY environment.yml /app/
RUN micromamba env create \
      --file environment.yml \
      --name property-val-env \
    && micromamba clean --all --yes

# Activate environment 
SHELL ["micromamba", "run", "-n", "property-val-env", "/bin/bash", "-lc"]

# Copy source code
COPY src/ /app/src/
ENV PYTHONPATH=/app/src
#ENV API_KEY=${API_KEY}

# Expose port 8000
EXPOSE 8000

# Run on container start
ENTRYPOINT ["micromamba", "run", "-n", "property-val-env", "/bin/bash", "-c", "uvicorn propval.api.main:app --host 0.0.0.0 --port 8000"]
