# This file defines the Conda environment for the propval pipeline:
#
# To create/update:
#   conda env create -f environment.yml
#   conda env update -f environment.yml

name: property-val-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - scikit-learn
  - fastapi
  - uvicorn
  - pydantic
  - pandera
  - prefect
  - python-dotenv
  - pip:
      - pytest
      - flake8
